 name: Build & Test Workflow

 on: 
       [pull_request]
 jobs:
   build:

     runs-on: windows-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 9.0

     - name: Restore workloads
       run: dotnet workload restore /workspace/RentalApp/RentalApp.csproj
